name: Build Python Artifact

on:
  push:
    branches:
      - main

  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build artifact
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload artifact to S3
        run: |
              aws s3 cp dist/app.zip s3://bucket1-javier-cardenas/
      - name: Upload GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-artifact
          path: dist/app.zip